### PR TITLE
Fixing deploy target in Makefile

### PR DESCRIPTION
**Pull request by bastinjul**

### CODE REVIEW

**Review by Laymer — COMMENTED** [review]
I think the `default.env` file that contains the `PEER_IP` variable is no longer mentioned in the `rebar.config` so I might need to include it in the config and test the deploy target first

**Comment by Laymer** [comment]
@bastinjul should we remove the `default.env` file if the `deploy` target works without it and merge this PR?

**Review by Laymer — APPROVED** [review]

**Review by Laymer — CHANGES_REQUESTED** [review]
@bastinjul can you just set the default commented deploy block in `rebar.config` to be the Linux one before we merge please? It will make less `diff`s from `master`

**Comment by bastinjul** [comment]
@Laymer It's done now

**Review by Laymer — APPROVED** [review]

**Comment by Laymer** [comment]
Awesome, thanks @bastinjul !

**Pull request merged**
